[theme]
primaryColor = "#4169E1"  # Royal Blue
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#F0F2F6"  # Light Gray
textColor = "#262730"  # Dark Gray
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50  # Allow uploads up to 50MB

[browser]
gatherUsageStats = false

[logger]
level = "info"

[deprecation]
showPyplotGlobalUse = false